# 线上配置文件
 # @from <a href="https://yupi.icu">编程导航知识星球</a>?useSSL=false'
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://62.234.214.59/user_center'
    username: root
    password: 365556835
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0

# [加入学习圈](https://t.zsxq.com/0emozsIJh) 从 0 到 1 项目实战，经验拉满！10+ 原创项目手把手教程、1000+ 项目经验笔记、7 日项目提升训练营、60+ 编程经验分享直播